version: '3'
name: chatbot

services:
  streamlit-app:
    container_name: streamlit_llama
    image: run_llama

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - .:/app